### ISSUE TITLE
Ruby native-image

### ISSUE THREAD

**Issue by sebyx07** [chrisseaton/graalvm-ten-things#1]
Can you use native-image with ruby?

**Comment by chrisseaton** [comment]
Do you mean, can you compile the Ruby interpreter with `native-image`? Yes.

Do you mean, can you compile Ruby applications to native code with `native-image`? No. Well, sort of. The TruffleRuby core library is implemented in Ruby, but we run the code that sets it up during compilation, and freeze the state of the application with the core library loaded, so that when we start running it's ready to go. Ruby code isn't compiled to native code, but Ruby code is run ahead-of-time and objects are created and alive when execution starts. This could in the future be extended to libraries, so you could compile a Ruby interpreter with your application pre-initialised.

**Comment by sebyx07** [comment]
Yes, I was asking if I could ship some ruby apps precompiled to a binary. For now I will stick mruby

**Comment by eregon** [comment]
Related: https://github.com/oracle/graal/issues/433#issuecomment-392248480

@sebyx07 So for you it's also important to have a single executable file with everything instead of an archive with a few files and an executable in it?

**Comment by sebyx07** [comment]
@eregon At least be able to bundle .rb files in one executable would be nice, like mruby.

Also I've managed to convert other file types at build time to base64 and explode them at startup.

example.html: "<html....."
=>
build/files/example.rb: ` EXAMPLE_HTML_FILE  = "aHRtbA==" `
=> 
convert it back and write the file.

Would be nice if there is a way to bundle

**Comment by chrisseaton** [comment]
Can you talk more about your use-case for this?

ruby is pretty small, but TruffleRuby is a few hundred MB, so does that fit what you'd want to do or would it be too large?

**Comment by sebyx07** [comment]
@chrisseaton Ah alright, then you can close this. I've thought the executable will at most 10mb. With mruby I get 2-3mb. Thanks for the info

**Comment by eregon** [comment]
> TruffleRuby is a few hundred MB

FWIW TruffleRuby 1.0.0-rc6 is ~150MB on disk uncompressed on Linux, and 42MB compressed.
In comparison, MRI 2.5.1 installed with `ruby-install` is also around 150MB uncompressed on disk on Linux (17MB `bin`, 83MB `lib` and 59MB `share`).

So yeah, both are definitely above 10MB.
MRuby is on purpose very minimal and e.g. only includes a subset of the core library and language functionalities (see [limitations](https://github.com/mruby/mruby/blob/master/doc/limitations.md)).
